compiler = "gcc"
std = ""
path = "bigtest/src"
files = ["arithmetic.cpp", "lexer.cpp", "logging.cpp", "main.cpp", "symbols.cpp", "utils.cpp"]
include = ["bigtest/src/include", "test"]
final = "./main"